export const DOSAGE_TYPE = {
    CAPSULE: 'capsule',
    TROCHE: 'troche',
    ORAL_LIQUID: 'oral_liquid',
    CREAM: 'cream',
    SUPPOSITORY: 'suppository',
    POWDER: 'powder'
  };

export const CREAM_INITIAL_INGREDIENTS = [ "SALICYLIC ACID , USP", "PROPYLENE GLYCOL", "SORBOLENE CREAM" ];
export const CREAM_INITAL_COMPOUND_NAME = "SALICYLIC ACID 12% TOPICAL CREAM"

export const CAPSULE_INITIAL_INGREDIENTS = [ "DHEA (DEHYDROEPIANDROSTERONE)", "SELENOMETHIONINE-L", "VITAMIN D3", "ZINC PICOLINATE", "MAGNESIUM GLYCINATE", "MICROCRYSTALLINE CELLULOSE" ];
export const CAPSULE_INITAL_COMPOUND_NAME = "DHEA 30MG, SELENOMETHIONINE-L 100MICROG, VITAMIN D3 2000IU, ZINC PICOLINATE 10MG, MAGNESIUM GLYCINATE 50MG CAPSULES"